name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: install and build
      run: |
        git submodule update --init --recursive
        npm install
        npm run build
      env:
        CI: true
