name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Use Node.js 13
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: install
      run: |
        npm install
    - name: build
      run: |
        npm run build
      env:
        CI: true
